version: '3.8'

services:
  
  php:
   build:
      context: ./docker/php
   volumes:
      - ./backend:/var/www/telegram-bot-support-platform
   working_dir: /var/www/telegram-bot-support-platform
   
  nginx:
    build:
      context: ./docker/nginx
    volumes:
    - ./frontend:/var/www/telegram-bot-support-platform
    working_dir: /var/www/telegram-bot-support-platform
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
  
    
  node:
    build:
      context: ./docker/node
    volumes:
      - ./frontend:/var/www/telegram-bot-support-platform
    working_dir: /var/www/telegram-bot-support-platform
    ports:
    - "5173:5173"
    # user: "node"
    # command: npm run dev
    # environment:
    #   - NODE_ENV=production
    # expose:
    #   - "8081"

#   redis:
#     image: redis
#     restart: always
#     ports: 
#      - "6379:6379"
#     volumes:
#       - /path/to/local/d–∞ta:/root/redis
#       - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
#     environment:
#        - REDIS_PASSWORD=12345
#        - REDIS_PORT=6379
#        - REDIS_DATABASES=16
    
#   centrifugal:
#       image: centrifugo/centrifugo
#       command: centrifugo -c config.json --engine=redis --redis_host=redis --redis_port=6379
#       volumes: 
#        - "./config:/centrifugo" 
#       ulimits:
#         nproc: 65536
#         nofile:
#           soft: 65536
#           hard: 65536
    
#   postgres:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example 